### ISSUE TITLE
Validation error in example programs

### ISSUE THREAD

**Issue by Silverlan** [GPUOpen-LibrariesAndSDKs/Anvil#64] opened 2018-03-16 14:01 UTC
When running one of the programs in the "examples" directory (I tried "DynamicBuffers" and "MultiViewport") with _ENABLE_VALIDATION_ defined, the programm will run, but also causes the following validation error:
```
[!] Object: 0x0 | vkCreateDescriptorPool: parameter pCreateInfo->poolSizeCount must be greater than 0. The spec valid usage text states 'poolSizeCount must be greater than 0' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkDescriptorPoolCreateInfo-poolSizeCount-arraylength)
```

**Comment by DominikWitczakAMD** [comment] 2018-03-16 14:15
Just as a sanity check - this is seen happening with a version of the validation layers, taken from the recently released Vulkan SDK, correct?

**Comment by Silverlan** [comment] 2018-03-16 15:18
Yes, I just updated Anvil, Vulkan and my GPU drivers (AMD) yesterday.

**Comment by DominikWitczakAMD** [comment] 2018-03-27 11:40
This issue does not reproduce with a fairly recent version of core validation layer, although I do recall seeing it in the past with older versions.

Can you please either:

1) Make sure to install the latest version of Vulkan SDK (https://www.lunarg.com/vulkan-sdk/), OR
2) Build the latest version of the layers manually (you can find them @ https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers) and then re-check?

Thanks.

**Comment by DominikWitczakAMD** [comment] 2018-03-31 20:47
Just discovered I hadn't been able to repro this issue because of a disabled ParameterValidation layer. Sigh. Apologies, will be looking at this shortly.

**Comment by DominikWitczakAMD** [comment] 2018-03-31 20:57
Fixed internally; a corresponding patch will be provided next week.

**Closed** 2018-04-13 06:25 UTC
Labels: bug, fixed internally
