### ISSUE TITLE
BasePipelineManager::Pipeline::release_vulkan_objects releases layout when shouldn't?

### ISSUE THREAD

**Issue by DeanoC** [GPUOpen-LibrariesAndSDKs/Anvil#3] opened 2016-08-01 10:23 UTC
> /*
>  *  The function does NOT release the layout object, since it's owned by the Pipeline Layout manager.
> */
> void Anvil::BasePipelineManager::Pipeline::release_vulkan_objects()

The comment say it doesn't release the layout but the code actually does. In my tests the code causes a crash, so I think the comment is right and the code wrong.

Not sure if just removing the release will cause leaks (though I've done that on my local copy at them mo.

**Comment by DominikWitczakAMD** [comment] 2016-08-09 07:10
Thanks for reporting this problem. We're currently in the process of moving to automated pointers, which may fix this issue, but I'm going to make sure the problem is addressed before we release an update.

**Comment by DominikWitczakAMD** [comment] 2016-08-31 10:11
Should be fixed in the next update.

**Closed by DominikWitczakAMD** 2016-08-31 10:11 UTC
Labels: bug
